### ISSUE TITLE
Unable to get extension to find Spacy.

### ISSUE THREAD

**Issue by MaximillianCat** [adieyal/sd-dynamic-prompts#181]
I was removing extensions to try to clear up errors occurring during startup and at the end of batch processing images.   I now encounter the following error as webui-user.bat starts

Spacy not installed, attention generator will not work. Install with pip install dynamicprompts[attentiongrabber]

Running that pip command does not resolve the issue.  Manually using pip to uninstall and reinstall Spacy doesn't resolve the issue.

Reproduction:

Delete \extensions\sd-dynamic-prompts
Reinstall using the extensions tab from webui.
Shut down the instance (terminate webui-user.bat)
Run webui-user.bat again
Observe 'Spacy not installed' comment during startup.

This is running on my machine and not a collab.

Expectation:
Normally this error doesn't occur.  I'm wondering if I missed a file or script that I need to delete to do a 'clean' install of dynamic prompts.

**Comment by UBBK** [comment]
yeah i have the same issue. And right now dynamic promps are not randomized within the same batch

**Comment by adieyal** [comment]
@MaximillianCat Do you get an error when you try to manually install spacy?

**Comment by MaximillianCat** [comment]
@adieyal No, pip says all the dependencies are there.  Tried a force reinstall of spacy too.  Still get the message when starting webui.  Does dynamic prompts store anything outside it's extension folder?

**Comment by UBBK** [comment]
dynamic prompts started to stop randomizing things in the same batch after i started getting this exact spacy error message too.

**Comment by adieyal** [comment]
I've just pushed an update which should fix this. You will need to manually uninstall dynamicprompts first. In the webui main directory, run
`venv/bin/python -m pip uninstall dynamicprompts`  

It will then reinstall dynamicprompts when you restart the webui. 

In case the command above doesn't work, perhaps try `python -m pip uninstall dynamicprompts` - I can't be sure of how your environment is set up.

**Comment by adieyal** [comment]
> @adieyal No, pip says all the dependencies are there. Tried a force reinstall of spacy too. Still get the message when starting webui. Does dynamic prompts store anything outside it's extension folder?

No - nothing outside that folder. What might be happening is the you aren't installing spacy using the same python environment as auto1111 is using. Instead of `python -m pip` try `venv/bin/python -m pip`

**Comment by MaximillianCat** [comment]
I suspect instructions I followed from: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Troubleshooting are culprit here.  I previously deleted the /venv folder to try to get a clean build on next run.  There is no /bin folder in my /venv, so this is likely user error and probably not a problem with the dynamic prompts extension.  I'll have to keep poking at it to fix it.

**Comment by MaximillianCat** [comment]
Setting 'set VENV_DIR=-' in webui-user.bat resolved the issue.  I think that got it to configure the system python environment.

**Comment by DrMacabre** [comment]
still not working here, i did everything mentioned here, even removed extension and reinstalled.
File "F:\Programs\stable-diffusion-webui\modules\scripts.py", line 347, in process
    script.process(p, *script_args)
  File "F:\Programs\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 328, in process
    generator = generator_builder.create_generator()
  File "F:\Programs\stable-diffusion-webui\extensions\sd-dynamic-prompts\prompts\generator_builder.py", line 138, in create_generator
    generator = AttentionGenerator(
  File "F:\Programs\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\attentiongenerator.py", line 24, in __init__
    spacy.load(MODEL_NAME)
NameError: name 'spacy' is not defined

**Comment by adieyal** [comment]
Have you tried `venv\bin\python -m pip install spacy`?

**Comment by DrMacabre** [comment]
> Have you tried `venv\bin\python -m pip install spacy`?

i don't know where to execute it, not from the original a1111 folder at least cause theres no bin in venv folder

**Comment by adieyal** [comment]
really? That's weird, I'm not familiar with how virtual environments work in Windows, but that seems broken to me. In that case, try simply `python -m pip install spacy`

**Comment by DrMacabre** [comment]
> really? That's weird, I'm not familiar with how virtual environments work in Windows, but that seems broken to me. In that case, try simply `python -m pip install spacy`

as others mentioned, all Requirements already satisfied.

**Comment by adieyal** [comment]
What's happening is that the python environment that runs auto1111 is missing the spacy dependency, for whatever reason. In most cases, it can be found in the venv folder. That your venv folder doesn't have a bin is strange. In any case, we need to find where auto's environment is. what is VENV_DIR set to in webui-user.bat?

**Comment by DrMacabre** [comment]
> what is VENV_DIR set to in webui-user.bat?

it's not set, there's nothing after set VENV_DIR=
its like this by default. im using standard python here, No anaconda install.

**Comment by DrMacabre** [comment]
> Can you please test it before I merge it into the main branch?

Done, magic prompt is working now. Thank you

**Comment by adieyal** [comment]
That's great
