### ISSUE TITLE
Combinations does not work when using Wildcard files

### ISSUE THREAD

**Issue by finasu** [adieyal/sd-dynamic-prompts#307]
**Describe the bug**
https://github.com/adieyal/sd-dynamic-prompts/blob/main/docs/SYNTAX.md
According to this page, the following notations are permitted I have used this to make sure it works as intended.
```{2$$opt1|opt2|opt3}``` ```{1-3$$opt1|opt2|opt3}```

I checked the "Need help?" in the web UI. The wildcard should be available as follows
```{2$$__artist__}```

I would expect this method to call two rows, but in fact it could only call one row.

**To Reproduce**

Prepare "quality_tags.txt".
```
masterpiece
best quality
high quality
ultra-detailed
```
This was then described and generated in the prompt. The output is only one line from the file.
```{2$$__quality_tags__}```

Also mention which checkboxes have been set.

Only the next two are chucked.
- Attention grabber
- Don't apply to negative prompts

**Are you using a local install or a colab?**

I am using a local install and the commit hash for the Web UI is as follows
Commit hash: 3715ece0adce7bf7c5e9c5ab3710b2fdc3848f39

**Expected behaviour**

In the above example, two lines are expected to be read from the next four lines.
```
masterpiece
best quality
high quality
ultra-detailed
```

**Comment by anonamooseface** [comment]
> Piggybacking on this issue as I believe it is related. I'm also seeing weird behavior with combinations and wildcards. All wildcards work fine on their own, however when trying to combine with combinations/combinatorial things seem to be behaving oddly. To reproduce I created two wildcard files, test1.txt and test2.txt.
> 
> Test1;
> 
> > house
> > barn
> > shed
> > church
> > shack
> 
> Test2;
> 
> > blue
> > red
> > green
> > yellow
> > brown
> 
> The prompt I'm testing with is;
> 
> {__test2__|__test2__} [old:dirty:0.5] {__test1__|__test1__|__test1__}
> 
> Also have tried;
> 
> __test2__ [old:dirty:0.5] {__test1__|__test1__|__test1__}
> 
> In both cases, test1 seems to be properly randomizing/combinatorializing. However test2 is picking blue every time. Additionally if I add additional wildcards, most seem to also only ever select one value and stick with it every generation. Basically, it seems to me that only one wildcard will actually randomize while using combinatoric prompting with multiple wildcards referenced.
> 
> I've tried with "Unlink seed from prompt" checked, but seems to make no difference. Currently I'm doing 4 max generations with 2 combo batches, which is reliably giving me 8 images each run, always selecting "blue" from test2.txt while seemingly randomizing entries for test1 from test1.txt.

Okay, this seems to have to do with limiting the max generations under the Dynamic Prompts settings in the main UI page (in Automatic1111). I tried just setting it to 0, and now it seems to create every possible combination of the above wildcards as expected. 

However it seems with combinatorial mode enabled (whether using the squiggly brackets or not), wildcards no longer behave as "wildcard" files (in the sense that the selections are no longer randomized), and instead will be run through as a list with the goal to make every combination in order they are listed in the text files. It will stop making these combinations when it either reaches the end of the possible combinations, or it reaches what is set for max generations (in my earlier examples, this is why it never got passed the color blue). 

I'm not sure this is related to the actual top level issue here, but wanted to make sure I clarified my situation. Maybe this is solved somehow in the Jinja template portion, though I'm not sure. Mainly I'm hoping for a way to call multiple wildcards initially, and then on subsequent generations/batches only randomize some of the called wildcards. Ideally something like;

> \_\_test2\_\_ [old:dirty:0.5] {\_\_test1\_\_|\_\_test1\_\_}

Where test2 will randomly select a value from its associated wildcard text, and then generate combinatoric batches while still **randomly** choosing entries from test1's text file until it reaches the max generations limit (or total possible limit, but preferably a way to limit it and also have it retain the randomization and not become programmatic with each combination). Maybe not possible? Am I missing something?

Anyway, love the extension, thank you so much for everything you've done so far. :)

**Comment by adieyal** [comment]
> Mainly I'm hoping for a way to call multiple wildcards initially, and then on subsequent generations/batches only randomize some of the called wildcards. Ideally something like;

Sounds like it is working as expected, combinatorial mode generates every possible prompt, including all values in wildcard files. There is however [new syntax](https://github.com/adieyal/dynamicprompts#samplers) which I think  will achieve what you want.

In combinatorial mode, try something like this

`__~test2__ [old:dirty:0.5] {__test1__|__test1__}`  note the added `~`

That will choose a random value from test2.txt while iterating through every value in test1.txt.

Similar syntax is available for variants,

`{~random_value1|random_value2} [old:dirty:0.5] {__test1__|__test1__}`

**Comment by Velour-Fog** [comment]
You can "git checkout 7bb4029" which is v2.5.0. The {2$$__wildcard__} format works there. 

I am a little confused how there's been so many updates, and that core functionality has been broken the entire time. With that version I can do {10$$__enhance__}, instead of __enhance__ __enhance__ __enhance__ __enhance__ __enhance__ __enhance__ __enhance__ __enhance__ __enhance__ __enhance__, lol.

also the suggestion of "{__wildcard__|__wildcard__}" wouldn't work in their case because that just picks 1 of the 2 options, and they are both the same option. They would have to do "__wildcard__, __wildcard__", and at that point, the dynamic prompt extension is no different from the standard https://github.com/AUTOMATIC1111/stable-diffusion-webui-wildcards extension.

**Comment by adieyal** [comment]
@Velour-Fog you should probably read this https://github.com/adieyal/sd-dynamic-prompts/blob/main/.github/CONTRIBUTING.md

**Comment by Velour-Fog** [comment]
Sorry for sounding rude, we all appreciate your extension, and know you don't owe us anything. It can however be hard to draw attention to certain things without coming across as demanding or unappreciative.

**Comment by adieyal** [comment]
I appreciate your response. The reason it is currently broken is that we made changes to the parser which were somewhat complicated. Re-implementing this feature immediately was not trivial at the time. Now that the updated parser has been released, I'll be able to get to fixing it.

**Comment by Gushousekai195** [comment]
I just installed this extension and am not happy that combinations are not working for wildcards. I hope this is fixed soon.

**Comment by GrabertSebastian** [comment]
> > Mainly I'm hoping for a way to call multiple wildcards initially, and then on subsequent generations/batches only randomize some of the called wildcards. Ideally something like;
> 
> Sounds like it is working as expected, combinatorial mode generates every possible prompt, including all values in wildcard files. There is however [new syntax](https://github.com/adieyal/dynamicprompts#samplers) which I think will achieve what you want.
> 
> In combinatorial mode, try something like this
> 
> `__~test2__ [old:dirty:0.5] {__test1__|__test1__}` note the added `~`
> 
> That will choose a random value from test2.txt while iterating through every value in test1.txt.
> 
> Similar syntax is available for variants,
> 
> `{~random_value1|random_value2} [old:dirty:0.5] {__test1__|__test1__}`

the '~' operator was exactly what I was looking for, thanks for adding it, love your work!

would it be possible (in the future) to select one(!) random value and then use/repeat it in multiple places in the whole prompt?
for example, I want to add a specific __~colors__ for flowers and decorations
writing "__~colors__ flowers, __~colors__ decorations" will yield two random colors from the wildcard file
I want both values to be the same random value from the wildcard file, smth like __*colors__
Creating a variable like __#flowers__ = __~flowers__ and then use __#flowers__ where needed would be nice, but maybe to much.

with best regards

**Comment by adieyal** [comment]
> > > Mainly I'm hoping for a way to call multiple wildcards initially, and then on subsequent generations/batches only randomize some of the called wildcards. Ideally something like;
> > 
> > 
> > Sounds like it is working as expected, combinatorial mode generates every possible prompt, including all values in wildcard files. There is however [new syntax](https://github.com/adieyal/dynamicprompts#samplers) which I think will achieve what you want.
> > In combinatorial mode, try something like this
> > `__~test2__ [old:dirty:0.5] {__test1__|__test1__}` note the added `~`
> > That will choose a random value from test2.txt while iterating through every value in test1.txt.
> > Similar syntax is available for variants,
> > `{~random_value1|random_value2} [old:dirty:0.5] {__test1__|__test1__}`
> 
> the '~' operator was exactly what I was looking for, thanks for adding it, love your work!
> 
> would it be possible (in the future) to select one(!) random value and then use/repeat it in multiple places in the whole prompt? for example, I want to add a specific `__~colors__` for flowers and decorations writing `__~colors__ flowers, __~colors__ decorations` will yield two random colors from the wildcard file I want both values to be the same random value from the wildcard file, smth like `__*colors__` Creating a variable like `__#flowers__ = __~flowers__` and then use `__#flowers__` where needed would be nice, but maybe to much.
> 
> with best regards

Good idea - will add that to the todo list. We do have a cyclical operator, it's not exactly what you want, but it's worth knowing about.

You can do something like 

`{~red|green|blue} {@circle|square}`

The `@` will then cycle through the values, so you can get something like
```
A green circle
A red square
A red circle
A blue square
....
```

That's useful if you want to use the same value in a number of places, e.g.
`A {~red|green|blue} {@circle|square} and a {~red|green|blue} {@circle|square}`

That will produce
```
A green circle and a blue circle
A blue square and a red square
A blue circle and a green circle
...
```

There have been a few requests for creating variables already so it's clearly a common use case.

If you're ready to explore jinja templates, you can certainly achieve what you want
```
{% with color =random_sample("__colours__") %}
    {% prompt %}
        {{ color }} flowers,{{ color }} decorations
    {% endprompt %}
{% endwith %}
```

They're a little more complicated, but the benefit is that you get a lot more flexibility. You can read more [here](https://github.com/adieyal/sd-dynamic-prompts/blob/main/jinja2.md)

**Comment by Mossbraker** [comment]
This probably isn't really the place to be posting this but, since this still appears to be broken, how would I write something like the following in jinja?
`A {-2$$__color__|__shape__} and a {1-2$$__color__|__shape__} with a {3-4$$__color__|__shape__}`
Which, if I understand correctly, should randomly select 0-2 items in the first combination (1-2 in the second, 3-4 in the third), any of which could be from the color or shape wildcard files, and it should not repeat options in the output if the number of options listed is large enough. Let's ignore the fact that this would mostly generate nonsense prompts.

**Comment by adieyal** [comment]
@finasu @Velour-Fog @Mossbraker There is a PR waiting for review that will fix this - https://github.com/adieyal/dynamicprompts/pull/54

**Comment by finasu** [comment]
@adieyal 
Thank you for your work! Thanks again everyone for the discussion.
sd-dynamic-prompts is something that can help me find my own style in creating illustrations with AI and make AI more powerful to generate unexpected and interesting illustrations.
I will enjoy using it.😊
