### ISSUE TITLE
When running dynamic prompts with batch size > 0, the whole batch runs with the same text

### ISSUE THREAD

**Issue by gymdreams8** [adieyal/sd-dynamic-prompts#544]
If the prompt is: `a man wearing {red|blue|yellow|green} shirt`, and I start a batch count of 50, batch size of 1, then the 50 generated image will all be one of the four colors, e.g. `a man wearing red shirt` 50 times.

What I would expect it to do instead is having all four colors randomized for the 50 count.

Is there any way to get around this limitation?

**Comment by TheAntiCamper** [comment]
I'm seeing this as well with wildcards. A few days ago "__hair-color__ hair" wildcard with batch count of 12 would give me 12 images with different hair colors. Now its giving me 12 images with the same 1 hair color.

**Comment by AnteMaxx** [comment]
I'm also experiencing this problem. Is this something that Adetailer needs to fix or Dynamic prompts?

**Comment by Bing-su** [comment]
Adetailer needs to fix

**Comment by jmilez** [comment]
I have the same problem, it appeared after updating dynamic prompts last week. But I don't have Adetailer installed...?  Have to use batch size of 1 to make it work.
I'm running SD 1.32.

**Comment by amurorei01** [comment]
Encountered the same promblem after dynamic prompts updated today.
Not sure whether the adetailer causes it or not.

**Comment by Nucklead** [comment]
Another observation.

If I have a fixed seed in main WebUI, but not in DynamicPrompts, wildcard substitution does work properly (i.e. chosen randomly each generation) but seed increases by 1 each time. This is the default behavior of combinatorial generation of dynamic prompts and, I think, it shouldn't be applied if this option is tuned off. Is this an intended?
<details><summary>Fixed Seed OFF Images</summary>
<p>

![1_0](https://github.com/adieyal/sd-dynamic-prompts/assets/42011240/aaf1157c-2568-47ff-8cf4-0e89f1f1d070)
![1_1](https://github.com/adieyal/sd-dynamic-prompts/assets/42011240/aba63af7-e4d9-4470-8581-b65d6ee842d9)

</p>
</details> 

On another hand, if Fixed Seed turned on in Advanced Settings of Dynamic Prompts, wildcard substitution isn't working.
<details><summary>Fixed Seed ON Images</summary>
<p>

![2_0](https://github.com/adieyal/sd-dynamic-prompts/assets/42011240/b83c8a10-c0cd-4fe3-9829-66f2111f5fd7)
![2_1](https://github.com/adieyal/sd-dynamic-prompts/assets/42011240/fc4ec38b-6ba7-4edd-8fc8-cbf5f311d351)


</p>
</details> 

I hope it helps to narrow down possible suspects.

SD as well as all extensions are updated to the latest version at the time of writing.

**Comment by adieyal** [comment]
Thanks for the reports, I'll look into it

**Comment by adieyal** [comment]
@Nucklead when setting fixed seed, try setting unlink seed from prompt. That will choose a random prompt but use the same seed for each image.

**Comment by adieyal** [comment]
@gymdreams8 @TheAntiCamper @AnteMaxx @jmilez 

Is this still an issue for you? I think adetailer has fixed this issue. I can't reproduce it.

**Comment by Nucklead** [comment]
> @Nucklead when setting fixed seed, try setting unlink seed from prompt. That will choose a random prompt but use the same seed for each image.

Tested it. Dynamic Prompts->Advanced Options->"Fixed Seed" and "Unlink Seed From Prompt" both ON works mostly as expected.

Generating with batch count of > 1:
With Combinatorial Generation ON - seed stays the same across all images, prompt has variations.
With Combinatorial Generation OFF - prompt has proper variations but seed increases by 1 with each image in the batch.

About the last one. I've no idea if this is the default behavior of Automatic1111 or something from Dynamic Prompts affects it.

Otherwise, with the "Unlink Seed From Prompt" the issue is resolved for me. Thank you.

**Comment by adieyal** [comment]
There is a PR that should fix this - I wrote it a while ago but haven't merged it in yet - https://github.com/adieyal/sd-dynamic-prompts/pull/552

**Comment by Nucklead** [comment]
So, basically, if I need randomized prompts with fixed seed, it is currently possible to use a workaround:
Dynamic Prompts->Advanced Options->"Fixed Seed" and "Unlink Seed From Prompt" both ON, Dynamic Prompts->Combinatorial Generation ON and set Maximum Generations to an amount of images desired.

A little side-effect of this method would be that wildcards\variants won't be exactly randomly chosen, but rather systematically iterated. To return to the pure randomness, if I understand this correctly, one would need to explicitly set "Random ~" sampler for every wildcard\variant. How to do this is explained in detailed documentation->"Samplers" section.

As for seed increment with batch count > 1 when seed is specified in the default WebUI - even with Dynamic Prompts extension turned off in the extensions tab, this increment still happens, so it looks like this is the default behavior of Automatic1111. I wouldn't notice it before because I wasn't paying attention to that, but now I know.

**Comment by barasalah2** [comment]
![image](https://github.com/adieyal/sd-dynamic-prompts/assets/122377189/3748f06e-eee3-4f4d-9ab6-1057bcf73a9c)
same issue here started happening two days ago.

**Comment by AIrtistry** [comment]
still have this issue, I have a wildcards who contain 12 colors, but one of them ( white ) appears on 90% of the images

**Comment by yeungmozhu** [comment]
When I use wildcards and select the combination generate, it always uses the first prompt.
